#! /bin/zsh
# vim: set ft=zsh:ts=2:et:


handler='head'
switches=(a x m)
useO='-o'
exclaxm=(a x m)
exclm=(m)
pthing=''
echo "Param count: $#"
while [ $# -gt 0 ]; do
  case $1 in
    --*)
      arg=${1#??}
      case $arg in
        all) handler='cat' ;;
        count=*) cutoff=${arg#count=};;
        *) "I don't know what $arg means"; exit 1 ;;
      esac
    ;;
    -*)
      args=${1#?}
      while [ ${#args} -gt 0 ]; do
        case ${args[1,1]} in
          a) handler='cat' ;;
          s) handler='aggregator' ;;
          p) 
            switches=${switches:|exclaxm} 
            shift
            pthing="-p $1"
            shift
            ;;
          # x) switches='' ;;
          n) switches=${switches:|exclm} ;;
          *) echo "I don't know what -${args[1,1]} means."; exit 2 ;;
        esac
        args=${args#?}
      done
    ;;
  esac
  [ $# -gt 0 ] && shift
done



# zmodload zsh/zutil || exit 11
# zparseopts -D -E -F -- \
#   {c, -cutoff}=cutoff
#  a:=arg_val -arg:=arg_val f=flag -flag=flag \
# 	F=foobar -foo=foobar B=foobar -bar=foobar || exit 1




psPrefs=${PS_PREFS:-pid,pmem,rss,cputime,ruser,ppid,ucomm,lstart}
finalSwitches=''
[ ${#switches} -gt 0 ] && finalSwitches=-${(j..)switches}
print "Final switches: $finalSwitches"
#  -o pid,pmem,rss,cputime,ruid,ppid,ucomm
putThis="$finalSwitches $pthing $useO $psPrefs"
print "Going to call sudo /bin/ps $putThis"
sudo /bin/ps $putThis | case $handler in
  'head')
    head -n ${cutoff:-15}
  ;;
  'cat')
    cat
  ;;
  'aggregator')
    ps_aggregator
  ;;
esac