#! /bin/zsh
# vim: set ft=zsh:ts=2:et:


handler='head'
switches=(a x m)
useO='-o'

echo "Param count: $#"
while [ $# -gt 0 ]; do
  case $1 in
    --*)
      arg=${1#??}
      case $arg in
        all) handler='cat' ;;
        count=*) cutoff=${arg#count=};;
        *) "I don't know what $arg means" ;;
      esac
    ;;
    -*)
      args=${1#?}
      while [ ${#args} -gt 0 ]; do
        case ${args[1,1]} in
          a) handler='cat' ;;
          s) handler='aggregator' ;;
          p) switches=(${switches:|(a x m)}); switches+=(p) ;;
          x) switches='' ;;
          *) echo "I don't know what -${args[1,1]} means." ;;
        esac
        args=${args#?}
      done
    ;;
  esac
  shift
done



# zmodload zsh/zutil || exit 11
# zparseopts -D -E -F -- \
#   {c, -cutoff}=cutoff
#  a:=arg_val -arg:=arg_val f=flag -flag=flag \
# 	F=foobar -foo=foobar B=foobar -bar=foobar || exit 1




psPrefs=${PS_PREFS:-pid,pmem,rss,cputime,ruser,ppid,ucomm,lstart}
#  -o pid,pmem,rss,cputime,ruid,ppid,ucomm
sudo /bin/ps -${(j..)switches} $useO $psPrefs | case $handler in
  'head')
    head -n ${cutoff:-15}
  ;;
  'cat')
    cat
  ;;
  'aggregator')
    ps_aggregator
  ;;
esac