#!/usr/bin/env /bin/zsh
# vim: set ft=zsh:ts=2:et:

be_quiet='QUIET'
if [ "$1" = '-v' ]; then
  be_quiet='LOUD'
  shift
fi

if >/dev/null type $1; then
  exit 0
elif alias | ggrep -ch $1; then
  exit 0
else
  if [ "$be_quiet" = 'LOUD' ]; then
    >&2 print "\n\033[93;1mERROR:  Missing \033[37m$1\033[0m"
  fi
  exit 1
fi
