#! /bin/zsh

be_quiet='QUIET'
if [ "$1" = '-v' ]; then
  be_quiet='LOUD'
  shift
fi

if >/dev/null type $1; then
  if [ "$be_quiet" = 'LOUD' ]; then
    >&2 print "\n\033[93;1mERROR: \033[37m$1 \033[93;1mis already occupied!"
    >&2 type -aS $1
  fi
  exit 1
else
  exit 0
fi
