#! /bin/zsh
# vim: set ft=zsh

be_quiet='QUIET'
if [ "$1" = '-v' ]; then
  be_quiet='LOUD'
  shift
fi

if >/dev/null type $1; then
  exit 0
else
  if [ "$be_quiet" = 'LOUD' ]; then
    >&2 print "\n\033[93;1mERROR:  Missing \033[37m$1"
  fi
  exit 1
fi
