#! /opt/homebrew/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/bin/python3
# vim: set ft=Python

import sys

for line in sys.stdin:
    if line[49] == 'W':
        sys.stdout.write(line)
        sys.stdout.flush()


