#! /bin/sh

appname=$1
if [ "$(expr $appname : '==>')" -lt 3 ] && [ "$(expr $appname : '^Casks')" -lt 3 ] && [ "$(expr $appname : '^Formulae')" -lt 6 ]; then
    # echo "Info for $appname"
    brew info $appname | gawk -v appname="$appname" -f "$HOME"/scripts/brew_info.gawk
fi