#! /bin/sh
# vim: set ft=sh:ts=2:et:

caveat_folder="$HOME"/Documents/data/caveat_output

xtime=$(gdate +%F.%H%M%S)

all_formulae="${caveat_folder}/${xtime}.formulae"
all_casks="${caveat_folder}/${xtime}.casks"

brew list --formulae -1 > "$all_formulae"
brew list --casks -1 > "$all_casks"

ffolder="${caveat_folder}/formulae"
cfolder="${caveat_folder}/casks"

mkdir -p "$ffolder"
mkdir -p "$cfolder"

do_formula(){
  its_name="$1"
  this_one="$ffolder/$1_f"
  [ -f "$this_one" ] && return;
  brew caveats "$its_name" > "$this_one"
}

while IFS= read -r name; do
  do_formula "$name" &
done <"$all_formulae"





