[style.logpercent]
color_000 = "BrightBlue|Blue"
color_001 = "BrightGreen|Green"
color_005 = "BrightYellow|Yellow"
color_010 = "BrightRed|Red"

[[columns]]
kind = "Pid"
style = "BrightYellow|Yellow"
numeric_search = true
nonnumeric_search = false
align = "Left"

[[columns]]
kind = "Ppid"
style = "BrightYellow|Yellow"
numeric_search = false
nonnumeric_search = true
align = "Left"

[[columns]]
kind = "CpuTime"
style = "BrightYellow|Yellow"
numeric_search = false
nonnumeric_search = true
align = "Left"

[[columns]]
kind = "ElapsedTime"
style = "BrightYellow|Yellow"
numeric_search = false
nonnumeric_search = true
align = "Left"

[[columns]]
kind = "VmRss"
style = "BrightYellow|Yellow"
numeric_search = false
nonnumeric_search = true
align = "Left"

[[columns]]
kind = "Tty"
style = "BrightWhite|Black"
numeric_search = false
nonnumeric_search = false
align = "Left"

[[columns]]
kind = "UsageCpu"
style = "logpercent"
numeric_search = false
nonnumeric_search = false
align = "Right"

[[columns]]
kind = "UsageMem"
style = "logpercent"
numeric_search = false
nonnumeric_search = false
align = "Right"

[[columns]]
kind = "Threads"
style = "BrightYellow|Yellow"
numeric_search = false
nonnumeric_search = true
align = "Left"

[[columns]]
kind = "Separator"
style = "BrightYellow|Yellow"
numeric_search = false
nonnumeric_search = true
align = "Left"

[[columns]]
kind = "MultiSlot"
style = "BrightYellow|Yellow"
numeric_search = false
nonnumeric_search = true
align = "Left"

[[columns]]
kind = "Separator"
style = "BrightYellow|Yellow"
numeric_search = false
nonnumeric_search = true
align = "Left"

[[columns]]
kind = "UserReal"
style = "BrightYellow|Yellow"
numeric_search = false
nonnumeric_search = true
align = "Left"

[[columns]]
kind = "Separator"
style = "BrightYellow|Yellow"
numeric_search = false
nonnumeric_search = true
align = "Left"

[[columns]]
kind = "ReadBytes"
style = "BrightYellow|Yellow"
numeric_search = false
nonnumeric_search = true
align = "Left"

[[columns]]
kind = "WriteBytes"
style = "BrightYellow|Yellow"
numeric_search = false
nonnumeric_search = true
align = "Left"

[[columns]]
kind = "Separator"
style = "BrightYellow|Yellow"
numeric_search = false
nonnumeric_search = true
align = "Left"

[[columns]]
kind = "Command"
style = "BrightYellow|Yellow"
numeric_search = false
nonnumeric_search = true
align = "Left"

[style]
header = "BrightWhite|Black"
unit = "BrightWhite|Black"
tree = "BrightWhite|Black"



[style.by_percentage]
color_000 = "BrightBlue|Blue"
color_025 = "BrightGreen|Green"
color_050 = "BrightYellow|Yellow"
color_075 = "BrightRed|Red"
color_100 = "BrightRed|Red"

[style.by_state]
color_d = "BrightRed|Red"
color_r = "BrightGreen|Green"
color_s = "BrightBlue|Blue"
color_t = "BrightCyan|Cyan"
color_z = "BrightMagenta|Magenta"
color_x = "BrightMagenta|Magenta"
color_k = "BrightYellow|Yellow"
color_w = "BrightYellow|Yellow"
color_p = "BrightYellow|Yellow"

[style.by_unit]
color_k = "BrightBlue|Blue"
color_m = "BrightGreen|Green"
color_g = "BrightYellow|Yellow"
color_t = "BrightRed|Red"
color_p = "BrightRed|Red"
color_x = "BrightBlue|Blue"

[search]
numeric_search = "Exact"
nonnumeric_search = "Partial"
logic = "And"

[display]
show_self = false
cut_to_terminal = true
cut_to_pager = false
cut_to_pipe = false
color_mode = "Auto"
separator = "│"
ascending = "▲"
descending = "▼"
tree_symbols = ["│", "─", "┬", "├", "└"]
abbr_sid = true



