#! /bin/zsh

doUs=(
arch
base64
basename
cat
chcon
chgrp
chmod
chown
chroot
cksum
comm
cp
csplit
cut
date
dd
df
dir
dircolors
dirname
du
echo
env
expand
expr
factor
false
fmt
fold
grep
groups
head
hostid
hostname
id
install
join
kill
link
ln
logname
ls
md5sum
mkdir
mkfifo
mknod
mktemp
mv
nice
nl
nohup
nproc
numfmt
od
paste
pathchk
pinky
pr
printenv
printf
ptx
pwd
readlink
realpath
rm
rmdir
runcon
sed
seq
shred
shuf
sleep
sort
split
stat
stdbuf
stty
sum
tac
tail
tee
test
timeout
touch
tr
true
truncate
tsort
tty
uname
unexpand
uniq
unlink
uptime
users
vdir
wc
who
whoami
yes
)

gbin="$HOME/Documents/scripts/rc/gbin"

for doMe in $doUs; do
  p="$(which -aS $doMe | grep -v ' ' | head -n1)"
  if [ ! -x "$p" ]; then
    print "\033[93;1mNOT EXECUTABLE: $p\033[0m"
  fi
  l="${gbin}/g${doMe}"
  if [ ! -f "$l" ]; then
    print "linking $p to: $l"
    ln -s "$p" "$l"
  else
    # print "link $l already exists."
  fi
done

chmod -R 777 "$gbin"