#! /bin/sh
# vim: set ft=sh:ts=2:et:


three='three'
if [ 'three' = "$three" ]; then echo 3; else echo 4; fi | xargs echo
four='four'
if [ 'three' = "$four"  ]; then echo 3; else echo 4; fi | xargs echo
