#! /bin/zsh
# vim: set ft=zsh:ts=2:et:


function checkMatch(){
    case $1 in
        <->)
            echo "$1 is number"
            ;;
        *)
            echo "$1 went to default."
    esac
}

checkMatch 2

