#! /bin/sh

function color_demo(){
    i=$1
    extras=$2
    end_num=$((i+7))
    # printf '  '
    while [ $i -le $end_num ]; do
        printf "\\033[${i}${extras}m  %s  " $i
        if [ $1 -lt 100 ]; then printf ' '; fi
        printf '\033[0m'
        i=$((i+1))
    done
    printf '\n'
}


color_demo 30 "$1"
color_demo 40 "$1"
color_demo 90 "$1"
color_demo 100 "$1"